# These are links to platforms where people can financially support your project.
# The 'sponsor' button will appear on your GitHub repository page.

ko_fi: marcorocha
custom: ['https://buymeacoffee.com/MarcoRocha']

